# Generated by Django 6.0.3 on 2026-04-03 19:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finance', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='financials',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='financials',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
