# Generated by Django 6.0.3 on 2026-04-03 20:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finance', '0002_alter_financials_created_at_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='financials',
            name='deleted_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='financials',
            name='is_deleted',
            field=models.BooleanField(default=False),
        ),
    ]
